/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/atras` | `/atras`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/delante` | `/delante`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/app`; params?: Router.UnknownInputParams; } | { pathname: `/src/detalle`; params?: Router.UnknownInputParams; } | { pathname: `/src/headerPlayers`; params?: Router.UnknownInputParams; } | { pathname: `/src/insert`; params?: Router.UnknownInputParams; } | { pathname: `/src/listado`; params?: Router.UnknownInputParams; } | { pathname: `/src/multimedia`; params?: Router.UnknownInputParams; } | { pathname: `/src/mystyles`; params?: Router.UnknownInputParams; } | { pathname: `/src/update`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase/databaseListener`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase/mensajes`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase/sendNotification`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/atras` | `/atras`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/delante` | `/delante`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/src/app`; params?: Router.UnknownOutputParams; } | { pathname: `/src/detalle`; params?: Router.UnknownOutputParams; } | { pathname: `/src/headerPlayers`; params?: Router.UnknownOutputParams; } | { pathname: `/src/insert`; params?: Router.UnknownOutputParams; } | { pathname: `/src/listado`; params?: Router.UnknownOutputParams; } | { pathname: `/src/multimedia`; params?: Router.UnknownOutputParams; } | { pathname: `/src/mystyles`; params?: Router.UnknownOutputParams; } | { pathname: `/src/update`; params?: Router.UnknownOutputParams; } | { pathname: `/src/firebase/databaseListener`; params?: Router.UnknownOutputParams; } | { pathname: `/src/firebase/firebase`; params?: Router.UnknownOutputParams; } | { pathname: `/src/firebase/mensajes`; params?: Router.UnknownOutputParams; } | { pathname: `/src/firebase/sendNotification`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/atras${`?${string}` | `#${string}` | ''}` | `/atras${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/delante${`?${string}` | `#${string}` | ''}` | `/delante${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/src/app${`?${string}` | `#${string}` | ''}` | `/src/detalle${`?${string}` | `#${string}` | ''}` | `/src/headerPlayers${`?${string}` | `#${string}` | ''}` | `/src/insert${`?${string}` | `#${string}` | ''}` | `/src/listado${`?${string}` | `#${string}` | ''}` | `/src/multimedia${`?${string}` | `#${string}` | ''}` | `/src/mystyles${`?${string}` | `#${string}` | ''}` | `/src/update${`?${string}` | `#${string}` | ''}` | `/src/firebase/databaseListener${`?${string}` | `#${string}` | ''}` | `/src/firebase/firebase${`?${string}` | `#${string}` | ''}` | `/src/firebase/mensajes${`?${string}` | `#${string}` | ''}` | `/src/firebase/sendNotification${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/atras` | `/atras`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/delante` | `/delante`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/app`; params?: Router.UnknownInputParams; } | { pathname: `/src/detalle`; params?: Router.UnknownInputParams; } | { pathname: `/src/headerPlayers`; params?: Router.UnknownInputParams; } | { pathname: `/src/insert`; params?: Router.UnknownInputParams; } | { pathname: `/src/listado`; params?: Router.UnknownInputParams; } | { pathname: `/src/multimedia`; params?: Router.UnknownInputParams; } | { pathname: `/src/mystyles`; params?: Router.UnknownInputParams; } | { pathname: `/src/update`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase/databaseListener`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase/mensajes`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase/sendNotification`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
